### PR TITLE
Show user access token only once

### PR DESCRIPTION
**Pull request by giosakti**
For user access token
- Only show access token once and stored it as hash
- add 'regenerate' function for token

### CODE REVIEW

**Comment by ajeygore** [comment]
I did not understand what did you do here? Basically I just wanted to show api_key and user access token ONLY in "New" once we have done we hash it and save it in database

Can you please explain as to what you have done here?

**Comment by giosakti** [comment]
that is what I did, basically:

1. show it only once for user, also put warning
2. hash it on db
3. for every token validation, we hash the token from the request and then match it to hashed token on db

I also added one function to `regenerate` the token. So if users for some reason lost their token, they can regenerate it by themselves.

**Comment by giosakti** [comment]
I separate 2 PR for this: one you already merged for api_key and this PR is for user access token

**Comment by ajeygore** [comment]
Got it. I am gonna go ahead merge the PR.

**Pull request merged**
